"""edit_Product

Revision ID: 206f6dfed20d
Revises: bf3b19148aaa
Create Date: 2023-12-29 18:11:59.777440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '206f6dfed20d'
down_revision = 'bf3b19148aaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Sale', 'New', 'BestSeller', name='selecttype').create(op.get_bind())
    op.add_column('product', sa.Column('type', postgresql.ENUM('Sale', 'New', 'BestSeller', name='selecttype', create_type=False), nullable=True))
    op.drop_column('product', 'saleBool')
    op.drop_column('product', 'newBool')
    op.drop_column('product', 'best_sellerBool')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('best_sellerBool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('newBool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('saleBool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('product', 'type')
    sa.Enum('Sale', 'New', 'BestSeller', name='selecttype').drop(op.get_bind())
    # ### end Alembic commands ###
