"""Product+columnt(Bool)

Revision ID: 29e0c4932aa6
Revises: 32d429a25f40
Create Date: 2023-07-21 11:13:37.376095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e0c4932aa6'
down_revision = '32d429a25f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('saleBool', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('newBool', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('best_sellerBool', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'best_sellerBool')
    op.drop_column('product', 'newBool')
    op.drop_column('product', 'saleBool')
    # ### end Alembic commands ###
