"""AddColumn_slug

Revision ID: 32d429a25f40
Revises: a05766eb4870
Create Date: 2023-07-08 17:21:09.720528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d429a25f40'
down_revision = 'a05766eb4870'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('order', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('subcategories', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategories', 'slug')
    op.drop_column('order', 'slug')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
