"""Subcategories+subcategories_id

Revision ID: a05766eb4870
Revises: 12ceb3ef3aaf
Create Date: 2023-06-30 13:58:38.021060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05766eb4870'
down_revision = '12ceb3ef3aaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('subcategories_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_subcategories_id', 'subcategories', 'subcategories', ['subcategories_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_subcategories_id', 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'subcategories_id')
    # ### end Alembic commands ###
