"""create_table_Storage

Revision ID: bf3b19148aaa
Revises: 16c464676189
Create Date: 2023-07-26 16:40:55.864317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3b19148aaa'
down_revision = '16c464676189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('city', sa.Enum('kem', 'nov', 'len', 'bel', name='selectcity'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_title'), 'address', ['title'], unique=True)
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['address.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id', 'address', 'product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    op.drop_index(op.f('ix_address_title'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
